=== ilyasToumlilt/PACS/TD06/annuaire.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT annuaire (elemcarnet*)>
<!ELEMENT elemcarnet (personne, adresse, telephone)>
<!ELEMENT personne (nom, prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT adresse (rue, ville)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT telephone (EMPTY)>

<!ATTLIST elemcarnet
   date CDATA #REQUIRED
>
<!ATTLIST personne
   sexe (M | F) #REQUIRED
>
<!ATTLIST rue
   numero CDATA #REQUIRED
>
<!ATTLIST ville
   codepostal CDATA #REQUIRED
>
<!ATTLIST telephone
   fixe CDATA #REQUIRED
>

=== ilyasToumlilt/PACS/TD06/annuaire.xml
<?xml version='1.0' encoding='iso-8859-15' standalone='no' ?>
<!DOCTYPE annuaire SYSTEM 'annuaire.dtd' >
<annuaire>
   <elemcarnet date='15-4-02'>
      <personne sexe='M'>
	 <nom> Archimede </nom>
	 <prenom> Pierre </prenom>
      </personne>
      <adresse>        
	 <rue numero="7"> du puissant liquide</rue>
	 <ville codepostal="76000"> Le Havre </ville>
      </adresse>
      <telephone fixe="03 77 66 55 44" mobile="" />
   </elemcarnet>
   <elemcarnet date='15-4-02'>
      <personne sexe='F'>
	 <nom> Hypatia </nom>
	 <prenom> Cléo </prenom>
      </personne>
      <adresse>
	 <rue numero="5"> d'Alexandrie </rue>
	 <ville codepostal="13000"> Marseille </ville>
      </adresse>
      <telephone fixe="04 11 22 33 44" mobile="06 55 44 22 11" />
   </elemcarnet>
</annuaire>
